/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(services)'}/queryClient` | `/queryClient`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/breaking` | `/breaking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/education` | `/education`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sports` | `/sports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trending` | `/trending`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(services)'}/queryClient` | `/queryClient`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/breaking` | `/breaking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/education` | `/education`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sports` | `/sports`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trending` | `/trending`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(services)'}/queryClient${`?${string}` | `#${string}` | ''}` | `/queryClient${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/breaking${`?${string}` | `#${string}` | ''}` | `/breaking${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/education${`?${string}` | `#${string}` | ''}` | `/education${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sports${`?${string}` | `#${string}` | ''}` | `/sports${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trending${`?${string}` | `#${string}` | ''}` | `/trending${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(services)'}/queryClient` | `/queryClient`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/breaking` | `/breaking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/education` | `/education`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sports` | `/sports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trending` | `/trending`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
